Documento Objetivo-0
jacarmona364/Riskalc pull request #1
Opened 2024-09-24 09:20 UTC by jacarmona364

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
* [x] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2024-09-25 17:21 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
> 
>     * [x]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?

¿Qué crees que has incluido y dónde lo has enlazado?
> 
>     * [x]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
>       a requerir que el usuario los introduzca?
> 
>     * [x]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
>       todo?

¿Cuál de los dos?

2024-09-25 22:33 UTC, jacarmona364 commented
@JJ este proyecto es uno de los puntos que voy a estar desarrollando en mis prácticas de empresa, ya estoy en contacto con la misma y me van a facilitar datos de operaciones pasadas con los que poder trabajar. Los subiré a mi repositorio en el mismo instante en que disponga de ellos.

2024-09-26 07:23 UTC, JJ commented
OK, pero sigues sin incluir la configuración para que me cerciore de que lo has hecho correctamente.

2024-09-27 11:44 UTC, JJ requested changes
No dependáis de que yo recuerda lo que me habéis contado, por favor.

2024-09-27 11:44 UTC, JJ commented on README.md
> +Soy el director del departamento de análisis de riesgos de una empresa de banca y mi problema es que no encuentro la forma de que mis empleados se pongan de acuerdo para establecer los criterios del
Más o menos por lo que hablaste tengo una idea de como se puede hacer esto, pero convendría que fueras un poco más preciso y añadieras todo el contexto que hablamos en clase.

2024-09-27 12:14 UTC, jacarmona364 commented
Listo para revisión. @JJ estaba esperando a recibir los datos pertinentes y agregarlos a la documentación para ya pedirle la revisión de todos los cambios, pero quizás con esto esté todo correcto por el momento.

2024-09-27 15:16 UTC, JJ approved these changes
:+1:

2024-09-27 15:32 UTC, merged